import { useState } from "react";

/**
 * LoginButton Component
 *
 * This component handles user authentication via Google OAuth in a Chrome extension.
 * It sends a message to the background script to initiate login and updates the UI
 * based on authentication status.
 *
 * Features:
 * - Displays a login button if the user is not authenticated.
 * - Sends a login request to the background script via `chrome.runtime.sendMessage`.
 * - Updates the UI to show user details upon successful login.
 * - Displays an error message if authentication fails.
 *
 * Authored by: Sebastian Yepez
 *
 * Documentation generated by ChatGPT
 *
 * @returns {JSX.Element} The LoginButton component UI.
 */
const LoginButton = () => {
  // State to store any login errors
  const [error, setError] = useState(null);

  /**
   * Handles the login process by sending a message to the background script.
   * - If authentication succeeds, updates the user state.
   * - If authentication fails, updates the error state.
   */
  /**
   * Initiates the Google login process and stores the user profile.
   */
  const handleLogin = () => {
    setError(null);

    try {
      chrome.runtime.sendMessage({ type: "LOGIN" }, (response) => {
        if (chrome.runtime.lastError) {
          setError(chrome.runtime.lastError.message || "Reopen Rebel Remind and try again.");
          return;
        }

        if (response?.success) {
          console.log("User logged in:", response.user);
          chrome.storage.sync.set({ user: response.user }); // Store user data
          chrome.storage.local.set({
            GoogleCalendarSyncStatus: {
              success: true,
              reason: "login_refreshed",
              updatedAt: new Date().toISOString(),
            },
          });
        } else {
          setError(response?.error || "Login failed.");
          console.error("Login failed:", response?.error);
        }
      });
    } catch (sendError) {
      setError(
        String(sendError?.message || "").includes("Extension context invalidated")
          ? "Rebel Remind was reloaded. Reopen the extension and try again."
          : sendError?.message || "Reopen Rebel Remind and try again."
      );
    }
  };

  return (
    <div>
      <button onClick={handleLogin}>Login with Google</button>
      {error && <p>{error}</p>}
    </div>
  );
};

export default LoginButton;
